akeneo_frontoffice:
    resource: @AkeneoFrontofficeBundle/Controller
    type: annotation

akeneo_api:
    resource: @AkeneoApiBundle/Resources/config/routing.yml
    prefix:   /api/

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

google_login:
    path: /login/check-google
